/* ==============================================
   VISHAL DRIVING SCHOOL — GOOGLE APPS SCRIPT
   PURPOSE: Auto-notify tutor via WhatsApp (CallMeBot),
   email (Gmail), and log leads to Google Sheet when a
   student submits the Google Form enrollment.

   HOW TO SET UP:
   1. Open the Google Sheet linked to your Form.
   2. Click Extensions → Apps Script.
   3. Delete any existing code and paste ALL of
      this file's contents.
   4. Fill in TUTOR_EMAIL, TUTOR_WHATSAPP, and
      CALLMEBOT_API_KEY below.
   5. Click Save (💾).
   6. Click Run → onFormSubmit once (authorize it).
   7. Click Triggers (⏰) → Add Trigger:
        Function:       onFormSubmit
        Event source:   From Spreadsheet
        Event type:     On form submit
   8. Save the trigger. Done!

   CALLMEBOT WHATSAPP SETUP (one-time, free):
   A. Save +34 644 39 92 39 as "CallMeBot" in tutor's
      WhatsApp contacts.
   B. Send this message to that contact on WhatsApp:
         I allow callmebot to send me messages
   C. Within ~2 minutes, CallMeBot replies with an
      API key (e.g. 1234567). Paste it below.
   ============================================== */

// ⬇️ REPLACE WITH TUTOR'S ACTUAL EMAIL
var TUTOR_EMAIL = "Bunty999sahu999@gmail.com";

// ⬇️ REPLACE WITH TUTOR'S WHATSAPP NUMBER (with country code, no + or spaces)
//    Example: "917877459724"
var TUTOR_WHATSAPP = "917877459724";

// ⬇️ REPLACE WITH THE API KEY RECEIVED FROM CALLMEBOT
var CALLMEBOT_API_KEY = "REPLACE_WITH_CALLMEBOT_API_KEY";

// School contact details
var SCHOOL_NAME  = "Vishal Driving School";
var SCHOOL_PHONE = "+91 7877459724";
var WHATSAPP_URL = "https://wa.me/917877459724";


/**
 * Triggered automatically every time a student
 * submits the Google Form.
 */
function onFormSubmit(e) {
  try {
    var responses  = e.namedValues;

    // --- Extract form fields ---
    // Edit keys to match your exact Google Form question titles
    var studentName  = getVal(responses, ["Student Name", "Name", "Full Name", "नाम"]);
    var studentPhone = getVal(responses, ["Phone Number", "Mobile", "Contact Number", "फोन नंबर"]);
    var carChoice    = getVal(responses, ["Car Choice", "Preferred Car", "Car", "कार"]);
    var batchPref    = getVal(responses, ["Batch Preference", "Batch", "Timing", "बैच"]);
    var city         = getVal(responses, ["City", "Location", "शहर"]);
    var timestamp    = new Date().toLocaleString("en-IN", {timeZone:"Asia/Kolkata"});

    // --- Build email subject ---
    var subject = "🚗 New Lead: " + studentName + " (" + city + ") — " + SCHOOL_NAME;

    // --- Build HTML email body ---
    var body = "<div style='font-family:sans-serif;max-width:520px;border:1px solid #eee;border-radius:12px;overflow:hidden;'>"
      + "<div style='background:linear-gradient(135deg,#f97316,#ef4444);padding:24px 28px;'>"
      + "<h2 style='color:#fff;margin:0;font-size:1.4rem;'>🎉 New Enrollment Request!</h2>"
      + "<p style='color:rgba(255,255,255,0.85);margin:6px 0 0;font-size:0.9rem;'>A new student wants to join " + SCHOOL_NAME + "</p>"
      + "</div>"
      + "<div style='padding:28px;'>"
      + row("👤 Student Name",  studentName)
      + row("📞 Phone Number",  studentPhone)
      + row("🚗 Car Selected",  carChoice)
      + row("⏰ Batch",         batchPref)
      + row("📍 City",          city)
      + row("🕐 Submitted At",  timestamp)
      + "<div style='background:#fff7ed;border:1px solid #fed7aa;border-radius:8px;padding:16px;margin-top:20px;'>"
      + "<p style='color:#c2410c;font-weight:600;margin:0 0 8px;'>⚡ Action Required</p>"
      + "<p style='color:#92400e;margin:0;font-size:0.9rem;'>Please call or WhatsApp <strong>" + studentName + "</strong> at <strong>" + studentPhone + "</strong> within 2 hours to confirm their seat.</p>"
      + "</div>"
      + "<div style='margin-top:24px;text-align:center;'>"
      + "<a href='tel:" + studentPhone.replace(/[^+\d]/g,'') + "' style='background:#f97316;color:#fff;text-decoration:none;border-radius:50px;padding:12px 28px;font-weight:700;font-size:0.9rem;display:inline-block;margin:4px;'>📞 Call Student</a>"
      + "<a href='" + WHATSAPP_URL + "' style='background:#25d366;color:#fff;text-decoration:none;border-radius:50px;padding:12px 28px;font-weight:700;font-size:0.9rem;display:inline-block;margin:4px;'>💬 WhatsApp</a>"
      + "</div>"
      + "</div>"
      + "<div style='background:#f1f5f9;padding:14px 28px;text-align:center;font-size:0.78rem;color:#94a3b8;'>"
      + SCHOOL_NAME + " | " + SCHOOL_PHONE + " | Auto-generated by enrollment system"
      + "</div></div>";

    // --- Send WhatsApp notification via CallMeBot (free) ---
    sendWhatsAppAlert(studentName, studentPhone, carChoice, batchPref, city, timestamp);

    // --- Send email ---
    GmailApp.sendEmail(TUTOR_EMAIL, subject, "", { htmlBody: body });

    // --- Log to Sheet ---
    logToSheet(studentName, studentPhone, carChoice, batchPref, city, timestamp);

  } catch (err) {
    Logger.log("Error in onFormSubmit: " + err.toString());
  }
}


/**
 * Sends an instant WhatsApp message to the tutor via CallMeBot API.
 * Free service — no Meta Business account required.
 * Tutor must complete the one-time CallMeBot activation (see setup above).
 */
function sendWhatsAppAlert(name, phone, car, batch, city, timestamp) {
  try {
    var message = "🚗 *New Enrollment - " + SCHOOL_NAME + "*\n\n"
      + "👤 Name: " + name + "\n"
      + "📞 Phone: " + phone + "\n"
      + "🚘 Car: " + car + "\n"
      + "⏰ Batch: " + batch + "\n"
      + "📍 City: " + city + "\n"
      + "🕐 Time: " + timestamp + "\n\n"
      + "⚡ Please call or WhatsApp the student within 2 hours!";

    // CallMeBot requires URL-encoded message
    var encodedMsg = encodeURIComponent(message);
    var url = "https://api.callmebot.com/whatsapp.php"
      + "?phone=" + TUTOR_WHATSAPP
      + "&text=" + encodedMsg
      + "&apikey=" + CALLMEBOT_API_KEY;

    var options = {
      method: "get",
      muteHttpExceptions: true
    };

    var response = UrlFetchApp.fetch(url, options);
    Logger.log("CallMeBot response: " + response.getContentText());
  } catch (err) {
    // WhatsApp failure should not break email/sheet logging
    Logger.log("WhatsApp alert error: " + err.toString());
  }
}


/** Helper: safely get first value from named values map */
function getVal(responses, keys) {
  for (var i = 0; i < keys.length; i++) {
    if (responses[keys[i]] && responses[keys[i]][0]) {
      return responses[keys[i]][0].trim();
    }
  }
  return "—";
}

/** Helper: build a table row for the HTML email */
function row(label, value) {
  return "<div style='display:flex;border-bottom:1px solid #f1f5f9;padding:10px 0;'>"
    + "<span style='color:#94a3b8;font-size:0.85rem;min-width:150px;'>" + label + "</span>"
    + "<span style='color:#1e293b;font-weight:600;font-size:0.9rem;'>" + (value || "—") + "</span>"
    + "</div>";
}

/**
 * Logs each new lead to the "Lead Tracker" sheet.
 * If the sheet doesn't exist, it creates it with headers.
 */
function logToSheet(name, phone, car, batch, city, timestamp) {
  var ss        = SpreadsheetApp.getActiveSpreadsheet();
  var sheetName = "Lead Tracker";
  var sheet     = ss.getSheetByName(sheetName);

  // Create tracking sheet if it doesn't exist
  if (!sheet) {
    sheet = ss.insertSheet(sheetName);
    var headers = [
      "Timestamp",
      "Student Name",
      "Phone Number",
      "City",
      "Car Choice",
      "Batch",
      "Lead Status",        // New / Contacted / Converted / Lost
      "Amount Received (₹)",
      "Total Course Price (₹)",
      "Payment Pending (₹)",
      "Notes"
    ];
    sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
    
    // Style header row
    var headerRange = sheet.getRange(1, 1, 1, headers.length);
    headerRange.setBackground("#f97316");
    headerRange.setFontColor("#ffffff");
    headerRange.setFontWeight("bold");
    headerRange.setFontSize(11);
    sheet.setFrozenRows(1);

    // Set column widths
    sheet.setColumnWidth(1,  180); // Timestamp
    sheet.setColumnWidth(2,  160); // Name
    sheet.setColumnWidth(3,  140); // Phone
    sheet.setColumnWidth(4,  120); // City
    sheet.setColumnWidth(5,  130); // Car
    sheet.setColumnWidth(6,  100); // Batch
    sheet.setColumnWidth(7,  120); // Status
    sheet.setColumnWidth(8,  160); // Amount Received
    sheet.setColumnWidth(9,  170); // Total Price
    sheet.setColumnWidth(10, 170); // Pending
    sheet.setColumnWidth(11, 200); // Notes

    // Add data validation for Lead Status column
    var statusRule = SpreadsheetApp.newDataValidation()
      .requireValueInList(["New", "Contacted", "Converted", "Lost"], true)
      .build();
    sheet.getRange("G2:G1000").setDataValidation(statusRule);
  }

  // Determine default course price
  var coursePrice = "5000";
  if (car && car.toLowerCase().indexOf("wagon") !== -1) {
    coursePrice = "4500";
  }

  // Append new lead row
  var newRow = [
    timestamp,
    name,
    phone,
    city,
    car,
    batch,
    "New",          // Default status
    "",             // Amount received (tutor fills in)
    coursePrice,    // Auto-set course price
    "",             // Pending auto-calculated by formula
    ""              // Notes
  ];
  var lastRow = sheet.getLastRow() + 1;
  sheet.getRange(lastRow, 1, 1, newRow.length).setValues([newRow]);

  // Auto-calculate pending = Total Price - Amount Received
  // Column J (10) = Column I (9) - Column H (8)
  sheet.getRange(lastRow, 10).setFormula("=IF(I" + lastRow + "<>\"\",I" + lastRow + "-H" + lastRow + ",\"\")");

  // Alternate row colors for readability
  if (lastRow % 2 === 0) {
    sheet.getRange(lastRow, 1, 1, 11).setBackground("#fff7ed");
  }
}

/**
 * Utility: Get monthly revenue summary.
 * Run manually from Apps Script editor to log monthly stats.
 */
function getMonthlyRevenueSummary() {
  var ss    = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName("Lead Tracker");
  if (!sheet) { Logger.log("Lead Tracker sheet not found."); return; }

  var data       = sheet.getDataRange().getValues();
  var now        = new Date();
  var thisMonth  = now.getMonth();
  var thisYear   = now.getFullYear();
  var totalLeads = 0, converted = 0, revenue = 0;

  for (var i = 1; i < data.length; i++) {
    var ts = new Date(data[i][0]);
    if (ts.getMonth() === thisMonth && ts.getFullYear() === thisYear) {
      totalLeads++;
      if (data[i][6] === "Converted") {
        converted++;
        revenue += parseFloat(data[i][7]) || 0;
      }
    }
  }

  var summary = "📊 Monthly Summary (" + now.toLocaleString('default',{month:'long'}) + " " + thisYear + ")\n"
    + "Total Leads:      " + totalLeads + "\n"
    + "Converted:        " + converted  + "\n"
    + "Revenue Received: ₹" + revenue.toLocaleString('en-IN');
  Logger.log(summary);
}
